### ISSUE TITLE
DXライブラリのインクルードディレクトリの設定などはCMakeLists.txtに記述してほしい

### ISSUE THREAD

**Issue by Nobu19800** [soutaFeb/RobotArmControl_RTC#1]
マニュアルのRobotArmGUIのビルドの手順で、Visual Studio上でインクルードディレクトリ、ライブラリディレクトリを設定していますが、ビルドにCMakeを使う場合はCMakeLists.txtに記述したほうが簡単です。

`src/CMakeLists.txt`で`include_directories`や`link_directories`のコマンドを使って設定するようにしたほうがいいと思います。

**Comment by soutaFeb** [comment]
ご指摘ありがとうございます。CMakeからパスを指定できるように設定しました。

**Comment by Nobu19800** [comment]
対応していただいてありがとうございます。
