### ISSUE TITLE
単位が分かりません

### ISSUE THREAD

**Issue by Nobu19800** [soutaFeb/RobotArmControl_RTC#2]
マニュアルのデータポートやコンフィギュレーションパラメータの説明で速度や位置に単位が書いていないため、`m\s`なのか、`km/h`なのかということが分かりません。

**Comment by soutaFeb** [comment]
分かりました。マニュアルのコンポーネント説明表に単位を追加いたしました。

**Comment by Nobu19800** [comment]
対応ありがとうございます。
