### ISSUE TITLE
手先位置のデータ型

### ISSUE THREAD

**Issue by Nobu19800** [soutaFeb/RobotArmControl_RTC#3]
AccelerationControllerのposition_outputというOutPortがTimedDoubleSeq型になっていますが、位置を扱うのであればTimedPoint3D型かTimedPose3D型を使ったほうがいいと思います。

**Comment by soutaFeb** [comment]
ありがとうございます。位置を扱うデータポートをTimedPoint3D型に変更しました。

**Comment by soutaFeb** [comment]
ありがとうございます。位置を扱うデータポートをTimedPoint3D型に変更しました。それに合わせてマニュアルも更新しました。

**Comment by Nobu19800** [comment]
データポートで入出力する距離などのデータはSI基本単位にする必要があるので、mmではなくmを使ったほうがいいです。

**Comment by soutaFeb** [comment]
ご指摘ありがとうございます。データポートで入出力する距離の単位をmmからｍに変更しました。

**Comment by Nobu19800** [comment]
確認しました。修正していただいてありがとうございます。
